# Generated by Django 5.1.7 on 2025-04-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_subproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='saled_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
