# Generated by Django 5.1.7 on 2025-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subproduct_saled_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='old_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
